version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    container_name: covid-backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: covid-frontend
    restart: unless-stopped
    depends_on:
      - backend
